#!/bin/bash

echo "🔍 Piksel Base - Setup Patikrinimas"
echo "===================================="

echo "✅ Supabase CLI įdiegtas ir projektas susietas!"
echo "✅ Duomenų bazės lentelės sukurtos!"
echo ""
echo "🔧 Ką daryti toliau:"
echo ""
echo "1. 📱 Sukurkite Storage Bucket:"
echo "   - Eikite į https://supabase.com/dashboard"
echo "   - Atidarykite savo projektą"
echo "   - Storage → New Bucket"
echo "   - Name: piksel-files"
echo "   - Public bucket: ✅ (pažymėkite)"
echo ""
echo "2. 🚀 Testuokite Sistemą:"
echo "   npm run dev"
echo "   Atidarykite: http://localhost:3000"
echo ""
echo "3. 📊 Patikrinkite Duomenis:"
echo "   - Supabase Dashboard → Table Editor"
echo "   - Turėtumėte matyti 'orders' lentelę"
echo "   - Turėtumėte matyti 9 užsakymus"
echo ""
echo "🎯 Sistema paruošta veikimui su Supabase!"
